name: Unit Tests

on:
  push:
    branches:
      - dev
      - master

  pull_request:
    branches:
      - master

jobs:
  test-backend:
    runs-on: ubuntu-latest

    services:
      mongo_db:
        image: mongo
        env:
          MONGO_INITDB_ROOT_USERNAME: test
          MONGO_INITDB_ROOT_PASSWORD: password
          MONGO_INITDB_DATABASE: test
        options: >-
          --health-cmd mongo
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 27017:27017

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          cd backend
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Django tests
        run: |
          cd backend
          coverage run manage.py test
      - name: Tests coverage
        run: |
          cd backend
          coverage report -m

  test-client:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [14]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: |
          cd client
          npm install
      - name: Run tests
        run: |
          cd client
          npm test -- --coverage
